public enum PoketudiantSpriteSource {
    PARLFOR,ISMAR,RIGOLAMOR,PROCRASTINO,COUCHTAR,NUIDEBOU,ALABOURRE,BUCHAFON,BELMENTION,PROMOMAJOR,ENSEIGNANT,
    PARLFOR_DOS,ISMAR_DOS,RIGOLAMOR_DOS,PROCRASTINO_DOS,COUCHTAR_DOS,NUIDEBOU_DOS,ALABOURRE_DOS,BUCHAFON_DOS,BELMENTION_DOS,PROMOMAJOR_DOS,ENSEIGNANT_DOS
}
